insert into questions (question, correct_answer, wrong_answers, category, difficulty) values
('What is the capital of France?', 'Paris', ARRAY['London', 'Berlin', 'Madrid'], 'geography', 'easy'),
('Which planet is known as the Red Planet?', 'Mars', ARRAY['Venus', 'Jupiter', 'Saturn'], 'science', 'easy'),
('In what year did World War II end?', '1945', ARRAY['1942', '1948', '1950'], 'history', 'medium'),
('Who wrote "Romeo and Juliet"?', 'William Shakespeare', ARRAY['Charles Dickens', 'Jane Austen', 'Mark Twain'], 'literature', 'medium'),
('What is the chemical symbol for gold?', 'Au', ARRAY['Ag', 'Fe', 'Cu'], 'science', 'easy'),
('Which country won the 2018 FIFA World Cup?', 'France', ARRAY['Brazil', 'Germany', 'Argentina'], 'sports', 'medium'),
('What is the largest ocean on Earth?', 'Pacific Ocean', ARRAY['Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean'], 'geography', 'easy'),
('Who was the first President of the United States?', 'George Washington', ARRAY['Thomas Jefferson', 'Abraham Lincoln', 'John Adams'], 'history', 'easy'),
('What is the hardest natural substance on Earth?', 'Diamond', ARRAY['Gold', 'Iron', 'Platinum'], 'science', 'medium'),
('Which of these is a primary color?', 'Red', ARRAY['Green', 'Purple', 'Orange'], 'general', 'easy'),
('What is the longest river in the world?', 'Nile', ARRAY['Amazon', 'Yangtze', 'Mississippi'], 'geography', 'medium'),
('In which sport would you perform a slam dunk?', 'Basketball', ARRAY['Tennis', 'Volleyball', 'Baseball'], 'sports', 'easy'),
('Who painted the Mona Lisa?', 'Leonardo da Vinci', ARRAY['Vincent van Gogh', 'Pablo Picasso', 'Claude Monet'], 'general', 'medium'),
('What is the smallest country in the world?', 'Vatican City', ARRAY['Monaco', 'San Marino', 'Liechtenstein'], 'geography', 'hard'),
('Which element is said to keep bones strong?', 'Calcium', ARRAY['Iron', 'Zinc', 'Potassium'], 'science', 'easy'),
('Who is known as the "Father of Computers"?', 'Charles Babbage', ARRAY['Alan Turing', 'Bill Gates', 'Steve Jobs'], 'technology', 'hard'),
('What year did the Titanic sink?', '1912', ARRAY['1905', '1920', '1931'], 'history', 'medium'),
('How many players are on a standard soccer team?', '11', ARRAY['9', '10', '12'], 'sports', 'easy'),
('What is the capital city of Japan?', 'Tokyo', ARRAY['Seoul', 'Beijing', 'Bangkok'], 'geography', 'easy'),
('Which scientist proposed the theory of general relativity?', 'Albert Einstein', ARRAY['Isaac Newton', 'Nikola Tesla', 'Galileo Galilei'], 'science', 'medium');
